# Generated by Django 4.0.4 on 2022-07-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_previous_reservation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='previous_reservation_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
